apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gitcall-docker-server-service
  labels:
    release: {{ .Release.Name | quote }}
    app: {{ .Values.helm.app | quote }}
    tier: {{ .Values.helm.tier | quote }}
spec:
  selector:
    release: {{ .Release.Name | quote }}
    app: {{ .Values.helm.app | quote }}
    tier: {{ .Values.helm.tier | quote }}
    http: "true"
  ports:
  - port: 2375
    protocol: TCP
    targetPort: 2375
  type: ClusterIP
